package com.vikaspandey.myapp.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.vikaspandey.myapp.db.User;
import com.vikaspandey.myapp.db.Topic;
import com.vikaspandey.myapp.db.Forum;
import com.vikaspandey.myapp.db.Post;

import com.vikaspandey.myapp.db.UserDao;
import com.vikaspandey.myapp.db.TopicDao;
import com.vikaspandey.myapp.db.ForumDao;
import com.vikaspandey.myapp.db.PostDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig topicDaoConfig;
    private final DaoConfig forumDaoConfig;
    private final DaoConfig postDaoConfig;

    private final UserDao userDao;
    private final TopicDao topicDao;
    private final ForumDao forumDao;
    private final PostDao postDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        topicDaoConfig = daoConfigMap.get(TopicDao.class).clone();
        topicDaoConfig.initIdentityScope(type);

        forumDaoConfig = daoConfigMap.get(ForumDao.class).clone();
        forumDaoConfig.initIdentityScope(type);

        postDaoConfig = daoConfigMap.get(PostDao.class).clone();
        postDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        topicDao = new TopicDao(topicDaoConfig, this);
        forumDao = new ForumDao(forumDaoConfig, this);
        postDao = new PostDao(postDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Topic.class, topicDao);
        registerDao(Forum.class, forumDao);
        registerDao(Post.class, postDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        topicDaoConfig.getIdentityScope().clear();
        forumDaoConfig.getIdentityScope().clear();
        postDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public TopicDao getTopicDao() {
        return topicDao;
    }

    public ForumDao getForumDao() {
        return forumDao;
    }

    public PostDao getPostDao() {
        return postDao;
    }

}
