package com.vikaspandey.myapp.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "FORUM".
 */
@Entity
public class Forum {

    @Id
    private Long id;
    private String title;
    private String description;
    private Integer topics_count;
    private Integer posts_count;
    private Long last_activity_at;
    private Boolean have_subforum;

    @Generated
    public Forum() {
    }

    public Forum(Long id) {
        this.id = id;
    }

    @Generated
    public Forum(Long id, String title, String description, Integer topics_count, Integer posts_count, Long last_activity_at, Boolean have_subforum) {
        this.id = id;
        this.title = title;
        this.description = description;
        this.topics_count = topics_count;
        this.posts_count = posts_count;
        this.last_activity_at = last_activity_at;
        this.have_subforum = have_subforum;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getTopics_count() {
        return topics_count;
    }

    public void setTopics_count(Integer topics_count) {
        this.topics_count = topics_count;
    }

    public Integer getPosts_count() {
        return posts_count;
    }

    public void setPosts_count(Integer posts_count) {
        this.posts_count = posts_count;
    }

    public Long getLast_activity_at() {
        return last_activity_at;
    }

    public void setLast_activity_at(Long last_activity_at) {
        this.last_activity_at = last_activity_at;
    }

    public Boolean getHave_subforum() {
        return have_subforum;
    }

    public void setHave_subforum(Boolean have_subforum) {
        this.have_subforum = have_subforum;
    }

}
