package com.vikaspandey.myapp.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER".
 */
@Entity
public class User {

    @Id
    private Long id;
    private String name;
    private String image;
    private String rank;
    private Integer current_dimes;
    private Integer karma;
    private Integer fpd_count;

    @Generated
    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    @Generated
    public User(Long id, String name, String image, String rank, Integer current_dimes, Integer karma, Integer fpd_count) {
        this.id = id;
        this.name = name;
        this.image = image;
        this.rank = rank;
        this.current_dimes = current_dimes;
        this.karma = karma;
        this.fpd_count = fpd_count;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getRank() {
        return rank;
    }

    public void setRank(String rank) {
        this.rank = rank;
    }

    public Integer getCurrent_dimes() {
        return current_dimes;
    }

    public void setCurrent_dimes(Integer current_dimes) {
        this.current_dimes = current_dimes;
    }

    public Integer getKarma() {
        return karma;
    }

    public void setKarma(Integer karma) {
        this.karma = karma;
    }

    public Integer getFpd_count() {
        return fpd_count;
    }

    public void setFpd_count(Integer fpd_count) {
        this.fpd_count = fpd_count;
    }

}
